python3 domain_adaptation.py UDA_SKETCH UDA_REAL &> logs_dinov2_vit_g14/SKETCHtoREAL.log 
python3 domain_adaptation.py UDA_PAINTING UDA_REAL &> logs_dinov2_vit_g14/PAINTINGtoREAL.log 
python3 domain_adaptation.py UDA_CLIPART UDA_REAL &> logs_dinov2_vit_g14/CLIPARTtoREAL.log 
python3 domain_adaptation.py UDA_INFOGRAPH UDA_REAL &> logs_dinov2_vit_g14/INFOGRAPHtoREAL.log 
python3 domain_adaptation.py UDA_QUICKDRAW UDA_REAL &> logs_dinov2_vit_g14/QUICKDRAWtoREAL.log 
python3 domain_adaptation.py UDA_REAL UDA_SKETCH &> logs_dinov2_vit_g14/REALtoSKETCH.log 
python3 domain_adaptation.py UDA_QUICKDRAW UDA_SKETCH &> logs_dinov2_vit_g14/QUICKDRAWtoSKETCH.log 
python3 domain_adaptation.py UDA_PAINTING UDA_SKETCH &> logs_dinov2_vit_g14/PAINTINGtoSKETCH.log 
python3 domain_adaptation.py UDA_CLIPART UDA_SKETCH &> logs_dinov2_vit_g14/CLIPARTtoSKETCH.log 
python3 domain_adaptation.py UDA_INFOGRAPH UDA_SKETCH &> logs_dinov2_vit_g14/INFOGRAPHtoSKETCH.log 
python3 domain_adaptation.py UDA_QUICKDRAW UDA_PAINTING &> logs_dinov2_vit_g14/QUICKDRAWtoPAINTING.log 
python3 domain_adaptation.py UDA_REAL UDA_PAINTING &> logs_dinov2_vit_g14/REALtoPAINTING.log 
python3 domain_adaptation.py UDA_SKETCH UDA_PAINTING &> logs_dinov2_vit_g14/SKETCHtoPAINTING.log 
python3 domain_adaptation.py UDA_CLIPART UDA_PAINTING &> logs_dinov2_vit_g14/CLIPARTtoPAINTING.log 
python3 domain_adaptation.py UDA_INFOGRAPH UDA_PAINTING &> logs_dinov2_vit_g14/INFOGRAPHtoPAINTING.log 
python3 domain_adaptation.py UDA_REAL UDA_INFOGRAPH &> logs_dinov2_vit_g14/REALtoINFOGRAPH.log 
python3 domain_adaptation.py UDA_QUICKDRAW UDA_INFOGRAPH &> logs_dinov2_vit_g14/QUICKDRAWtoINFOGRAPH.log 
python3 domain_adaptation.py UDA_PAINTING UDA_INFOGRAPH &> logs_dinov2_vit_g14/PAINTINGtoINFOGRAPH.log 
python3 domain_adaptation.py UDA_CLIPART UDA_INFOGRAPH &> logs_dinov2_vit_g14/CLIPARTtoINFOGRAPH.log 
python3 domain_adaptation.py UDA_SKETCH UDA_INFOGRAPH &> logs_dinov2_vit_g14/SKETCHtoINFOGRAPH.log 
python3 domain_adaptation.py UDA_REAL UDA_CLIPART &> logs_dinov2_vit_g14/REALtoCLIPART.log 
python3 domain_adaptation.py UDA_QUICKDRAW UDA_CLIPART &> logs_dinov2_vit_g14/QUICKDRAWtoCLIPART.log 
python3 domain_adaptation.py UDA_PAINTING UDA_CLIPART &> logs_dinov2_vit_g14/PAINTINGtoCLIPART.log 
python3 domain_adaptation.py UDA_INFOGRAPH UDA_CLIPART &> logs_dinov2_vit_g14/INFOGRAPHtoCLIPART.log 
python3 domain_adaptation.py UDA_SKETCH UDA_CLIPART &> logs_dinov2_vit_g14/SKETCHtoCLIPART.log 
python3 domain_adaptation.py UDA_REAL UDA_QUICKDRAW &> logs_dinov2_vit_g14/REALtoQUICKDRAW.log 
python3 domain_adaptation.py UDA_CLIPART UDA_QUICKDRAW &> logs_dinov2_vit_g14/CLIPARTtoQUICKDRAW.log 
python3 domain_adaptation.py UDA_PAINTING UDA_QUICKDRAW &> logs_dinov2_vit_g14/PAINTINGtoQUICKDRAW.log 
python3 domain_adaptation.py UDA_INFOGRAPH UDA_QUICKDRAW &> logs_dinov2_vit_g14/INFOGRAPHtoQUICKDRAW.log 
python3 domain_adaptation.py UDA_SKETCH UDA_QUICKDRAW &> logs_dinov2_vit_g14/SKETCHtoQUICKDRAW.log 
